name: Bundle, zip and release on Github
on:
  push:
    branches:
      - master
      - main
jobs:
  publish:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: npm install

      - name: Bundle with Webpack
        run: npm run build

      - name: Zip release files
        uses: vimtor/action-zip@v1
        with:
          files: dist
          recursive: true
          dest: release.zip

      - uses: oprypin/find-latest-tag@v1
        id: latest_tag
        with:
          repository: gamersclub-booster/gamersclub-booster
          releases-only: false
          prefix: "v"

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ steps.latest_tag.outputs.tag }}
          tag: ${{ steps.latest_tag.outputs.tag }}
          artifacts: "release.zip"
          allowUpdates: true
          body: ${{github.event.head_commit.message}}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Release ${{ steps.latest_tag.outputs.tag }}
          path: dist
