name: Download release and upload to Firefox Store
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish:
    name: Release to Firefox Store
    runs-on: ubuntu-latest
    steps:
      - name: Download Github release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "gamersclub-booster/gamersclub-booster"
          version: "latest"
          file: "release.zip"
          target: "release.xpi"
          
      - name: Retrieve manifest.json
        run: unzip -p release.xpi manifest.json >manifest.json

      - name: Upload to Firefox Store
        uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: ${{ secrets.FIREFOX_STORE_UUID }}
          xpi-path: "release.xpi"
          self-hosted: false
          jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}
